### ISSUE TITLE
font-size & font-weigths & spacing classes?

### ISSUE THREAD

**Issue by rikschennink** [Frankwarnaar/minor-cssttr#7]
Veel van de selectors worden voorzien van bovenstaande classes, de CSS wordt er niet leesbaarder op. 

Let op. CSS is wat er uiteindelijk beoordeeld wordt. Het is op dit moment lastig deze CSS te beoordelen.

```css
.font-size-xxs,
nav .list-item--has-children > a:after {
  font-size: calc(0.95em / (1.2 * 1.2 * 1.2));
}
.font-size-xs {
  font-size: calc(0.95em / (1.2 * 1.2));
}
.font-size-sm,
h6,
input,
textarea,
.chat footer {
  font-size: calc(0.95em / (1.2));
}
.font-size-base,
body {
  font-size: 0.95em;
}
.font-size-md,
h5,
button {
  font-size: calc(0.95em * (1.2));
}
.font-size-lg,
h4 {
  font-size: calc(0.95em * (1.2 * 1.2));
}
.font-size-xl,
h3 {
  font-size: calc(0.95em * (1.2 * 1.2 * 1.2));
}
.font-size-xxl,
h2 {
  font-size: calc(0.95em * (1.2 * 1.2 * 1.2 * 1.2));
}
.font-size-xxxl,
h1 {
  font-size: calc(0.95em * (1.2 * 1.2 * 1.2 * 1.2 * 1.2));
}
```

Dit is niet heel duidelijk.
